### ISSUE TITLE
question about spec-constants

### ISSUE THREAD

**Issue by jinz2014** [lfmeadow/spec-constants#1]
Is the SYCL feature equivalent to constant memory in CUDA ? Thanks.

**Comment by lfmeadow** [comment]
No, it isn't. It is really a way to specialize kernels by providing constant values for some parameters that affect code generation. There are some good examples somewhere in the Intel documentation (sorry, I don't work directly on SYCL anymore so I can't remember where it was).

I suggest you contact Codeplay software: https://codeplay.com/company/contact/ . I know that they are considering a method to access CUDA constant memory.

Good luck.
